// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCemgqQB8bgkEM4yQLhED6K1gjiJxLfaj0',
    appId: '1:580377130505:web:90b7c4e1b434f16cc8ead8',
    messagingSenderId: '580377130505',
    projectId: 'first-app-f86e5',
    authDomain: 'first-app-f86e5.firebaseapp.com',
    storageBucket: 'first-app-f86e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBayGwPPFwqOeM8gAPK7x9T1P3wndAYbU',
    appId: '1:580377130505:android:e95c0b53bffc86fcc8ead8',
    messagingSenderId: '580377130505',
    projectId: 'first-app-f86e5',
    storageBucket: 'first-app-f86e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwZ6LGxVw_0mCNYjlpa82HS_jtK45SbV8',
    appId: '1:580377130505:ios:943a70570dab01f1c8ead8',
    messagingSenderId: '580377130505',
    projectId: 'first-app-f86e5',
    storageBucket: 'first-app-f86e5.appspot.com',
    iosClientId:
        '580377130505-ecl2529s84m73t0p3ohcfak9d1203hht.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwZ6LGxVw_0mCNYjlpa82HS_jtK45SbV8',
    appId: '1:580377130505:ios:943a70570dab01f1c8ead8',
    messagingSenderId: '580377130505',
    projectId: 'first-app-f86e5',
    storageBucket: 'first-app-f86e5.appspot.com',
    iosClientId:
        '580377130505-ecl2529s84m73t0p3ohcfak9d1203hht.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSignup',
  );
}
